### ISSUE TITLE
[BUG] Cannot run with the latest transformer release.

### ISSUE THREAD

**Issue by buptsad** [OptimalScale/LMFlow#913]
**Describe the bug**
ModuleNotFoundError: No module named 'transformers.deepspeed'.

**To Reproduce**
1. Follow the setup guide
2. download a database imdb
3. run the code
```
bash ./scripts/run_finetune_with_lisa.sh \
  --model_name_or_path /etc/dtol/mds/CausalLM-7B \
  --dataset_path data/imdb/train \
  --output_model_path output_models/finetuned_imdb_CausalLM-7B \
  --lisa_activated_layers 1 \
  --lisa_interval_steps 20
```

**Expected behavior**
idk

**Additional context**
Works fine with transformers v4.45.2.

**Comment by wheresmyhair** [comment]
Hi, thanks for interested in LMFlow! Could you please provide the call stack from the error message?

**Comment by buptsad** [comment]
> Hi, thanks for interested in LMFlow! Could you please provide the call stack from the error message?

```
[2024-10-29 14:59:57,308] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/usr/share/lflw/LMFlow/examples/finetune.py", line 29, in <module>
    from lmflow.models.auto_model import AutoModel
  File "/usr/share/lflw/LMFlow/src/lmflow/models/auto_model.py", line 6, in <module>
    from lmflow.models.hf_decoder_model import HFDecoderModel
  File "/usr/share/lflw/LMFlow/src/lmflow/models/hf_decoder_model.py", line 33, in <module>
    from transformers.deepspeed import HfDeepSpeedConfig
ModuleNotFoundError: No module named 'transformers.deepspeed'
```

And some more attempts trying to import deepspeed in python console: 
```
>>> from transformers import deepspeed
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'deepspeed' from 'transformers' (/etc/dtol/mambaforge/envs/test/lib/python3.9/site-packages/transformers/__init__.py)
>>> from transformers.integrations import deepspeed

```

It seems that in the latest release `deepspeed` has been moved into `transformers.integrations` :)

**Comment by wheresmyhair** [comment]
Solved in the latest pr #905
